#!/bin/sh

# Copyright (C) 2005 MaNGOS <http://www.mangosproject.org/>
#
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without
# modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

if test -z "`automake --version 2>&1|head -n 1|egrep '1.[5-9]'`"; then
        echo "Sorry, automake 1.5 or above is required.";
        exit 1;
fi

if test -z "`aclocal --version 2>&1|head -n 1|egrep '1.[5-9]'`"; then
        echo "Sorry, aclocal 1.5 or above is required.";
        exit 1;
fi

if test -z "`autoconf --version 2>&1|head -n 1|egrep '2.5'`"; then
        echo "Sorry, autoconf 2.5 or above is required.";
        exit 1;
fi

if test -z "`autoheader --version 2>&1|head -n 1|egrep '2.5'`"; then
        echo "Sorry, autoheader 2.5 or above is required.";
        exit 1;
fi

rm -f config.cache
echo "- aclocal."
aclocal
echo "- autoconf."
autoconf
echo "- autoheader."
autoheader
echo "- automake."
automake -a -c
exit
